#!/usr/bin/env python3
import sys

try:
    cmd, input_file_name, output_file_name = sys.argv
except ValueError:
    print(f'{sys.argv[0]} [in] [out]')
    exit(-1)

input = open(input_file_name, 'rb')
output = open(output_file_name, 'w')

for x in input.read():
    blob = f"{x:02X}"
    output.write(blob)

print(f"Wrote {output.tell()} bytes to _{output_file_name}_.")

