#!/usr/bin/env python3

import sys


try:
    cmd, input_file_name, output_file_name = sys.argv
except ValueError:
    print(f'{sys.argv[0]} [in] [out]')
    exit(-1)

input = open(input_file_name, 'r')
output = open(output_file_name, 'wb')

mem = input.read()

for i in range(0,len(mem),2):
    x = f"{mem[i]}{mem[i+1]}"
    i = int(x, 16)
    output.write(i.to_bytes())

print(f"Wrote {len(mem)} bytes to _{output_file_name}_.")

