#!/usr/bin/env python3

import cv2
import sys


def decode_qr(image_path):
    img = cv2.imread(image_path)
    detector = cv2.QRCodeDetector()

    data, points, straight_qrcode = detector.detectAndDecode(img)

    if straight_qrcode is None or len(straight_qrcode) == 0:
        return "No qr code detected."
    else:
        return data

if __name__ == '__main__':
    code = decode_qr(sys.argv[1])
    print(code)

